# Generated by Django 2.2.1 on 2019-05-30 22:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallerDeportivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('dia', models.IntegerField()),
                ('hora', models.IntegerField()),
            ],
            managers=[
                ('talleres', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='TalleresDeportivo',
        ),
    ]
