# Generated by Django 2.2.1 on 2019-06-07 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deportes', '0004_auto_20190606_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservamusculatura',
            name='nombre',
        ),
        migrations.AddField(
            model_name='reservamusculatura',
            name='estudiante',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
