# Generated by Django 2.2.1 on 2019-06-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0005_auto_20190607_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallerdeportivo',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado')], max_length=10),
        ),
    ]
