# Generated by Django 2.2.1 on 2019-06-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0006_auto_20190607_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallerdeportivo',
            name='icono',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='icons/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tallerdeportivo',
            name='hora',
            field=models.TimeField(),
        ),
    ]
