# Generated by Django 2.2.1 on 2019-06-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0010_auto_20190609_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservamusculatura',
            name='bloque',
            field=models.TimeField(),
        ),
    ]
