# Generated by Django 2.2.1 on 2019-06-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0012_reservamusculatura_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservamusculatura',
            name='Fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
