# Generated by Django 2.2.1 on 2019-06-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0013_auto_20190610_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservamusculatura',
            name='Fecha',
            field=models.DateField(null=True),
        ),
    ]
