# Generated by Django 2.2.1 on 2019-06-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0014_auto_20190610_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservamusculatura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
