# Generated by Django 2.2.1 on 2019-06-18 01:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('servicioAcademico', '0002_auto_20190617_2118'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='numeroa',
            managers=[
                ('numeros', django.db.models.manager.Manager()),
            ],
        ),
    ]
