# Generated by Django 2.2.1 on 2019-06-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicioAcademico', '0003_auto_20190617_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaa',
            name='numeros',
            field=models.ManyToManyField(blank=True, to='servicioAcademico.NumeroA'),
        ),
    ]
