# Generated by Django 2.2.1 on 2019-06-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicioAcademico', '0005_numeroa_activo'),
    ]

    operations = [
    ]
