# Generated by Django 2.2.1 on 2019-06-26 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicioAcademico', '0006_auto_20190626_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaa',
            name='actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicioAcademico.NumeroA'),
        ),
        migrations.AlterField(
            model_name='diaa',
            name='numeros',
            field=models.ManyToManyField(blank=True, related_name='lista_numeros', to='servicioAcademico.NumeroA'),
        ),
    ]
