# Generated by Django 2.2.1 on 2019-06-27 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicioAcademico', '0007_auto_20190626_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaa',
            name='numeros',
            field=models.ManyToManyField(blank=True, related_name='lista_numerosA', to='servicioAcademico.NumeroA'),
        ),
        migrations.CreateModel(
            name='NumeroT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('numeros', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NumeroF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('numeros', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DiaT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField(null=True)),
                ('actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicioAcademico.NumeroT')),
                ('numeros', models.ManyToManyField(blank=True, related_name='lista_numerosT', to='servicioAcademico.NumeroT')),
            ],
            managers=[
                ('dias', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DiaF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField(null=True)),
                ('actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicioAcademico.NumeroF')),
                ('numeros', models.ManyToManyField(blank=True, related_name='lista_numerosF', to='servicioAcademico.NumeroF')),
            ],
            managers=[
                ('dias', django.db.models.manager.Manager()),
            ],
        ),
    ]
