# Generated by Django 2.2.1 on 2019-06-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='rut',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='sede',
            field=models.CharField(blank=True, default='Antonio Varas', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, default='Pregrado', max_length=10),
        ),
    ]
