# Generated by Django 2.2.1 on 2019-06-20 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicioAcademico', '0004_auto_20190620_1804'),
        ('accounts', '0002_auto_20190603_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='horatomada',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='servicioAcademico.NumeroA'),
        ),
    ]
