# Generated by Django 2.2.1 on 2019-06-20 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_horatomada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='horatomada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicioAcademico.NumeroA'),
        ),
    ]
