# Generated by Django 2.2.1 on 2019-06-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190620_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='horatomada',
        ),
    ]
