# Generated by Django 2.2.1 on 2019-06-28 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicioAcademico', '0008_auto_20190627_1648'),
        ('accounts', '0007_profile_horatomada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='horatomada',
            new_name='horatomadaA',
        ),
        migrations.AddField(
            model_name='profile',
            name='horatomadaF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicioAcademico.NumeroF'),
        ),
        migrations.AddField(
            model_name='profile',
            name='horatomadaT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicioAcademico.NumeroT'),
        ),
    ]
