# Generated by Django 2.2.1 on 2019-06-07 04:45

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('hora_inicio', models.IntegerField()),
                ('hora_cierre', models.IntegerField()),
                ('descripcion', models.CharField(max_length=300)),
            ],
            managers=[
                ('salas', django.db.models.manager.Manager()),
            ],
        ),
    ]
