# Generated by Django 2.2.1 on 2019-06-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_nuevasala'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NuevaSala',
        ),
    ]
